export const UPDATE_SELECTED_CATEGORY = 'UPDATE_SELECTED_CATEGORY'
export const UPDATE_SEARCH_KEYWORD = 'UPDATE_SEARCH_KEYWORD'

// Api call
export const UPDATE_SEARCH_RESULT = 'UPDATE_SEARCH_RESULT'

// Api call monitoring
export const UPDATE_FETCHING = 'UPDATE_FETCHING'
export const UPDATE_SUCCESS = 'UPDATE_SUCCESS'
export const UPDATE_FAIL = 'UPDATE_FAIL'

