export const UPDATE_SELECTED_CATEGORY = 'UPDATE_SELECTED_CATEGORY'
export const UPDATE_SEARCH_KEYWORD = 'UPDATE_SEARCH_KEYWORD'
export const UPDATE_SUGGESTIONS = 'UPDATE_SUGGESTIONS'
export const UPDATE_FOCUS_KEYWORD_INPUT = 'UPDATE_FOCUS_KEYWORD_INPUT'

// Api call
export const UPDATE_SEARCH_RESULT = 'UPDATE_SEARCH_RESULT'

// Api call monitoring
export const UPDATE_FETCHING = 'UPDATE_FETCHING'
export const UPDATE_SUCCESS = 'UPDATE_SUCCESS'
export const UPDATE_FAIL = 'UPDATE_FAIL'
export const UPDATE_FETCHING_SUGGESTION = 'UPDATE_FETCHING_SUGGESTION'
export const UPDATE_FETCHING_SUGGESTION_SUCCESS = 'UPDATE_FETCHING_SUGGESTION_SUCCESS'
export const UPDATE_FETCHING_SUGGESTION_FAIL = 'UPDATE_FETCHING_SUGGESTION_FAIL'

// Stopping autoScroll
export const UPDATE_STOP_AUTO_SCROLL = 'UPDATE_STOP_AUTO_SCROLL'

// Auto Suggestion control
export const UPDATE_SHOW_AUTO_SUGGESTION = 'UPDATE_SHOW_AUTO_SUGGESTION'
