export const UPDATE_SELECTED_CATEGORY = 'UPDATE_SELECTED_CATEGORY'
export const UPDATE_SEARCH_KEYWORD = 'UPDATE_SEARCH_KEYWORD'

// Updating search results
export const UPDATE_PERSON = 'UPDATE_PERSON'
export const UPDATE_FILM = 'UPDATE_FILM'
export const UPDATE_PLANET = 'UPDATE_PLANET'
export const UPDATE_SPECIES = 'UPDATE_SPECIES'
export const UPDATE_STARSHIP = 'UPDATE_STARSHIP'
export const UPDATE_VEHICLE = 'UPDATE_VEHICLE'
